---
- name: testing docker devops flow
  gather_facts: no
  hosts: localhost
  tasks:

    - name: build a docker imgage
      command: docker build -t my_image:latest .
      args:
        chdir: flask_app/
      become: yes

    - name: check if container exist or not
      command: docker ps -f name=my_container1
      register: result

    - name: debug result
      debug:
        var: result

    - name: debug test
      debug:
        msg: 'yes'
      when:
        - result.stdout_lines|count == 2

    - name: run container if already exists
      shell: |
         docker stop my_container
         docker rm my_container
         docker run -d --name "my_container" -p 5000:5000 my_image
      become: yes
      when:
        - result.stdout_lines|count == 2

    - name: run a new container
      shell: |
         docker run -d --name "my_container" -p 5001:5000 my_image
      become: yes
      when:
        - result.stdout_lines|count == 1
